### ISSUE TITLE
Transfer power

### ISSUE THREAD

**Issue by EuPhobos** [KJeff01/Cobra-AI#11]
Just playing in dual with 1.40 (lastest master game branch), durning match he is transfer power to me.
It is stragne than bot "give money" to the enemy, like trying to bribe me? )
Most likely you forgot to put allianceExistsBetween() somewhere in code.

**Comment by KJeff01** [comment]
Wow. This is bigger than you think it was. It was an issue with calling multiple functions that cache their results in the same function. This could lead to a "race-condition" like scenario and dubious results could be returned.

My [function](https://github.com/KJeff01/Cobra/blob/e0a4101c795ca8eea41d1cb764f02936978c1327/multiplay/skirmish/cobra_includes/tactics.js#L459) to donate power did such a thing so sometimes the ally array could be swapped with the results of the enemy array. Thus donating power, sometimes, to what the bot thought was an ally.

Should be fixed with e0a4101c795ca8eea41d1cb764f02936978c1327. I can't ascertain any negative impact from this so far...

**Comment by KJeff01** [comment]
From my test this doesn't happen anymore. Closing.
